In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('student_data.csv')

In [4]:
print(df)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

print(type(df))

In [5]:
student_id=df['StudentID']

In [6]:
print(student_id)

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object

In [7]:
name=df['FullName']

In [8]:
print(name)

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

# Different file loading in pandas

In [9]:
# csv file
csv_file=pd.read_csv('student_data.csv')
print(csv_file)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [10]:
#excel file
excel_file=pd.read_excel('Demographic Health Dataset.xlsx')
print(excel_file)

          age         income      height      weight  score  gender  \
0   53.314588   46154.444558  163.419921   76.123791     63  Female
1   17.966176   60062.928092  160.731189   44.461246     79    Male
2   34.444523   44231.081305  154.878956   85.437335     99    Male
3   38.840654   58356.921121  148.451433   77.088962     53    Male
4   34.673053   38702.931453  173.231706   73.840446     67  Female
..        ...            ...         ...         ...    ...     ...
95  34.339202  150000.000000  168.475817   62.157100     67  Female
96  22.889838  180000.000000  159.602403   63.697198     55    Male
97  28.481639  200000.000000  157.216953   65.773231     86  Female
98  35.473987  250000.000000  166.958453  150.000000     97    Male
99  26.395866  300000.000000  155.216272  180.000000     62    Male

   target_class    category
0       Healthy  Category C
1       Healthy  Category A
2       Healthy  Category C
3     Unhealthy  Category C
4     Unhealthy  Category A
..          ...         ...
95      Healthy  Category A
96    Unhealthy  Category A
97      Healthy  Category C
98      Healthy  Category A
99    Unhealthy  Category A

[100 rows x 8 columns]

In [11]:
print(type(excel_file))

<class 'pandas.core.frame.DataFrame'>

# Basic functionalities of Pandas

In [12]:
df=pd.read_csv('student_data.csv')
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [13]:
df.head() #first five rows
df.head(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

In [14]:
df.tail() #last values

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [15]:
#column
df.columns
col=list(df.columns)
print(col)

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']

In [16]:
#index 
import numpy as np
df.index
index=np.array(df.index)
print(index)
print(index.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [18]:
df.sample(10)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

In [19]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [20]:
df.isnull().sum()

StudentID               0
FullName                0
Data Structure Marks    4
Algorithm Marks         4
Python Marks            5
CompletionStatus        0
EnrollmentDate          0
Instructor              0
Location                0
dtype: int64

# Transforming to dataframe from in built datas

In [21]:
my_list=[['Nadim',23],['Munad',23],['Salman', 22]]

In [22]:
list_df=pd.DataFrame(my_list,columns=['Name','Age'],index=[1,2,3])
print(type(list_df))
list_df

<class 'pandas.core.frame.DataFrame'>

     Name  Age
1   Nadim   23
2   Munad   23
3  Salman   22

In [23]:
my_tuple=(('Nadim',23),('salman',22),('Munad',24))
tuple_df=pd.DataFrame(my_tuple,columns=['Name','Age'])
tuple_df

     Name  Age
0   Nadim   23
1  salman   22
2   Munad   24

In [24]:
my_dict={
    'Name':['Nadim', 'Munad','salman'], 
    'Age':[23,23,22]
}
dict_df=pd.DataFrame(my_dict)
dict_df

     Name  Age
0   Nadim   23
1   Munad   23
2  salman   22

In [25]:
my_data=[
    {'Name': 'Nadim', 'Age':23, 'City':'Sylhet'},
    {'Name': 'Salman', 'Age':22, 'City':'Sylhet'},
    {'Name': 'Fahim', 'Age':23, 'City':'Barcelona'}
]
dat_df=pd.DataFrame(my_data)
dat_df

     Name  Age       City
0   Nadim   23     Sylhet
1  Salman   22     Sylhet
2   Fahim   23  Barcelona

# Accessing Values of Dataframe

In [26]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [30]:
df['FullName']
df['Data Structure Marks']

0     85.0
1     92.0
2     88.0
3     78.0
4      NaN
5     75.0
6     80.0
7     81.0
8     72.0
9     89.0
10     NaN
11    85.0
12    75.0
13     NaN
14    86.0
15    94.0
16    90.0
17    88.0
18     NaN
19    86.0
Name: Data Structure Marks, dtype: float64

In [32]:
#loc[row(index),column(features)] 
df.loc[0]

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [33]:
df.loc[:2] #multiple row (range)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

In [34]:
df.loc[5:]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [35]:
#multiiple row(normallist)
df.loc[[2,3,19]]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [36]:
df.loc[:,'Python Marks'] #all rows single column

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [41]:
df.loc[:,['FullName','Algorithm Marks']]

            FullName  Algorithm Marks
0        Alif Rahman             85.0
1      Fatima Akhter             92.0
2      Imran Hossain             88.0
3   Jannatul Ferdous             78.0
4        Kamal Uddin              NaN
5        Laila Begum             75.0
6     Mahmudul Hasan             80.0
7        Nadia Islam             81.0
8         Omar Faruq             72.0
9       Priya Sharma             89.0
10      Rahim Sheikh              NaN
11   Sadia Chowdhury             85.0
12      Tanvir Ahmed             75.0
13        Urmi Akter              NaN
14      Wahiduzzaman             86.0
15      Ziaur Rahman             94.0
16       Afsana Mimi             90.0
17       Babul Ahmed             88.0
18      Faria Rahman              NaN
19        Nasir Khan             86.0

In [42]:
#row with columns 
df.loc[3:7,'Python Marks']

3    82.0
4    95.0
5    78.0
6     NaN
7    85.0
Name: Python Marks, dtype: float64

# Changing index and columns and iloc

In [44]:
df_index=df.set_index('StudentID')
df_index

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [45]:
df_index.iloc[3:7] #loc will show error because it is no longer numeric

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka

In [46]:
df_index.iloc[:,1:3]

           Data Structure Marks  Algorithm Marks
StudentID
PH1001                     85.0             85.0
PH1002                     92.0             92.0
PH1003                     88.0             88.0
PH1004                     78.0             78.0
PH1005                      NaN              NaN
PH1006                     75.0             75.0
PH1007                     80.0             80.0
PH1008                     81.0             81.0
PH1009                     72.0             72.0
PH1010                     89.0             89.0
PH1011                      NaN              NaN
PH1012                     85.0             85.0
PH1013                     75.0             75.0
PH1014                      NaN              NaN
PH1015                     86.0             86.0
PH1016                     94.0             94.0
PH1017                     90.0             90.0
PH1018                     88.0             88.0
PH1019                      NaN              NaN
PH1020                     86.0             86.0

In [48]:
#changing columns
df.rename(columns={'FullName':'Full Name'})

,StudentID,Full Name,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

# changing values and iteration

In [49]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [51]:
df.drop(0,inplace=True)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [60]:
#column deletion 
df.drop('EnrollmentDate',axis=1,inplace=True)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Dhaka

In [61]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Dhaka

In [64]:
#value assign
df.loc[1,'Python Marks']=95

In [65]:
df.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
1,PH1002,Fatima Akhter,92.0,92.0,95.0,In Progress,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi

In [69]:
df.loc[1:3,'Python Marks']+=2
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
1,PH1002,Fatima Akhter,92.0,92.0,101.0,In Progress,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,91.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,88.0,Completed,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi

In [70]:
for i,series in df.iterrows():
    print(f"{i} :{series}")

1 :StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                    101.0
CompletionStatus          In Progress
Location                   Chattogram
Name: 1, dtype: object
2 :StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     91.0
CompletionStatus            Completed
Location                        Dhaka
Name: 2, dtype: object
3 :StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        88.0
CompletionStatus               Completed
Location                          Sylhet
Name: 3, dtype: object
4 :StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   95.0
CompletionStatus        In Progress
Location                 Chattogram
Name: 4, dtype: object
5 :StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   78.0
CompletionStatus          Completed
Location                   Rajshahi
Name: 5, dtype: object
6 :StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
Location                         Dhaka
Name: 6, dtype: object
7 :StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   85.0
CompletionStatus          Completed
Location                 Chattogram
Name: 7, dtype: object
8 :StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  76.0
CompletionStatus         Completed
Location                     Dhaka
Name: 8, dtype: object
9 :StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    88.0
CompletionStatus           Completed
Location                      Sylhet
Name: 9, dtype: object
10 :StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    91.0
CompletionStatus         In Progress
Location                      Khulna
Name: 10, dtype: object
11 :StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       87.0
CompletionStatus              Completed
Location                     Chattogram
Name: 11, dtype: object
12 :StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    79.0
CompletionStatus           Completed
Location                       Dhaka
Name: 12, dtype: object
13 :StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
Location                   Rajshahi
Name: 13, dtype: object
14 :StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    84.0
CompletionStatus           Completed
Location                       Dhaka
Name: 14, dtype: object
15 :StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
Location                  Chattogram
Name: 15, dtype: object
16 :StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   93.0
CompletionStatus          Completed
Location                      Dhaka
Name: 16, dtype: object
17 :StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   85.0
CompletionStatus          Completed
Location                     Sylhet
Name: 17, dtype: object
18 :StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
Location                  Chattogram
Name: 18, dtype: object
19 :StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  89.0
CompletionStatus         Completed
Location                     Dhaka
Name: 19, dtype: object

In [72]:
for i in df.itertuples():
    print(i)

Pandas(Index=1, StudentID='PH1002', FullName='Fatima Akhter', _3=92.0, _4=92.0, _5=101.0, CompletionStatus='In Progress', Location='Chattogram')
Pandas(Index=2, StudentID='PH1003', FullName='Imran Hossain', _3=88.0, _4=88.0, _5=91.0, CompletionStatus='Completed', Location='Dhaka')
Pandas(Index=3, StudentID='PH1004', FullName='Jannatul Ferdous', _3=78.0, _4=78.0, _5=88.0, CompletionStatus='Completed', Location='Sylhet')
Pandas(Index=4, StudentID='PH1005', FullName='Kamal Uddin', _3=nan, _4=nan, _5=95.0, CompletionStatus='In Progress', Location='Chattogram')
Pandas(Index=5, StudentID='PH1006', FullName='Laila Begum', _3=75.0, _4=75.0, _5=78.0, CompletionStatus='Completed', Location='Rajshahi')
Pandas(Index=6, StudentID='PH1007', FullName='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', Location='Dhaka')
Pandas(Index=7, StudentID='PH1008', FullName='Nadia Islam', _3=81.0, _4=81.0, _5=85.0, CompletionStatus='Completed', Location='Chattogram')
Pandas(Index=8, StudentID='PH1009', FullName='Omar Faruq', _3=72.0, _4=72.0, _5=76.0, CompletionStatus='Completed', Location='Dhaka')
Pandas(Index=9, StudentID='PH1010', FullName='Priya Sharma', _3=89.0, _4=89.0, _5=88.0, CompletionStatus='Completed', Location='Sylhet')
Pandas(Index=10, StudentID='PH1011', FullName='Rahim Sheikh', _3=nan, _4=nan, _5=91.0, CompletionStatus='In Progress', Location='Khulna')
Pandas(Index=11, StudentID='PH1012', FullName='Sadia Chowdhury', _3=85.0, _4=85.0, _5=87.0, CompletionStatus='Completed', Location='Chattogram')
Pandas(Index=12, StudentID='PH1013', FullName='Tanvir Ahmed', _3=75.0, _4=75.0, _5=79.0, CompletionStatus='Completed', Location='Dhaka')
Pandas(Index=13, StudentID='PH1014', FullName='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', Location='Rajshahi')
Pandas(Index=14, StudentID='PH1015', FullName='Wahiduzzaman', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', Location='Dhaka')
Pandas(Index=15, StudentID='PH1016', FullName='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', Location='Chattogram')
Pandas(Index=16, StudentID='PH1017', FullName='Afsana Mimi', _3=90.0, _4=90.0, _5=93.0, CompletionStatus='Completed', Location='Dhaka')
Pandas(Index=17, StudentID='PH1018', FullName='Babul Ahmed', _3=88.0, _4=88.0, _5=85.0, CompletionStatus='Completed', Location='Sylhet')
Pandas(Index=18, StudentID='PH1019', FullName='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', Location='Chattogram')
Pandas(Index=19, StudentID='PH1020', FullName='Nasir Khan', _3=86.0, _4=86.0, _5=89.0, CompletionStatus='Completed', Location='Dhaka')

# Sorting dataframe

In [73]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
1,PH1002,Fatima Akhter,92.0,92.0,101.0,In Progress,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,91.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,88.0,Completed,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Dhaka

In [76]:
copy=df.sort_values('Data Structure Marks',ascending=False)
copy

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,101.0,In Progress,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,91.0,Completed,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,88.0,Completed,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram

In [78]:
copy=df.sort_values(['Data Structure Marks','Algorithm Marks'])
copy

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,88.0,Completed,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,Chattogram
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,91.0,Completed,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,Sylhet
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,101.0,In Progress,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram

# filtering data based on condition

In [81]:
not_started=df.loc[df['CompletionStatus']=='Not Started']
not_started

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,Chattogram

In [90]:
completed_dsmarks=df.loc[(df['CompletionStatus']=='Completed') & (df['Data Structure Marks']>=90)]
completed_dsmarks

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,Location
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,Dhaka