In [3]:
import pandas as pd

# Phase 1: Load and Explore the Dataset)

In [4]:
df=pd.read_csv('tested.csv')

In [5]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [6]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",male,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",female,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",male,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",female,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",male,21.0,2,0,A/4 48871,24.1500,NaN,S

In [7]:
#display the lastt 5 rows 
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [8]:
#dataset shape 
df.shape

(418, 12)

In [9]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [10]:
#convert to list 
list(df.columns)

['PassengerId',
 'Survived',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [11]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [12]:
df.info #Dataset Information

<bound method DataFrame.info of      PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]>

In [13]:
df.describe() #statistical summary

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [14]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,418.000000,418.000000,418.000000,418,418,332.000000,418.000000,418.000000,418,417.000000,91,418
unique,NaN,NaN,NaN,418,2,NaN,NaN,NaN,363,NaN,76,3
top,NaN,NaN,NaN,"Kelly, Mr. James",male,NaN,NaN,NaN,PC 17608,NaN,B57 B59 B63 B66,S
freq,NaN,NaN,NaN,1,266,NaN,NaN,NaN,5,NaN,3,270
mean,1100.500000,0.363636,2.265550,NaN,NaN,30.272590,0.447368,0.392344,NaN,35.627188,NaN,NaN
std,120.810458,0.481622,0.841838,NaN,NaN,14.181209,0.896760,0.981429,NaN,55.907576,NaN,NaN
min,892.000000,0.000000,1.000000,NaN,NaN,0.170000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,996.250000,0.000000,1.000000,NaN,NaN,21.000000,0.000000,0.000000,NaN,7.895800,NaN,NaN
50%,1100.500000,0.000000,3.000000,NaN,NaN,27.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,1204.750000,1.000000,3.000000,NaN,NaN,39.000000,1.000000,0.000000,NaN,31.500000,NaN,NaN
max,1309.000000,1.000000,3.000000,NaN,NaN,76.000000,8.000000,9.000000,NaN,512.329200,NaN,NaN

In [15]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [16]:
report = {
    "Shape": df.shape,
    "Columns": df.columns.tolist(),
    "Data Types": df.dtypes,
    "Statistics": df.describe(),
    "Summary": df.describe(include="all")
}

report

{'Shape': (418, 12),
 'Columns': ['PassengerId',
  'Survived',
  'Pclass',
  'Name',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Ticket',
  'Fare',
  'Cabin',
  'Embarked'],
 'Data Types': PassengerId      int64
 Survived         int64
 Pclass           int64
 Name               str
 Sex                str
 Age            float64
 SibSp            int64
 Parch            int64
 Ticket             str
 Fare           float64
 Cabin              str
 Embarked           str
 dtype: object,
 'Statistics':        PassengerId    Survived      Pclass         Age       SibSp  \
 count   418.000000  418.000000  418.000000  332.000000  418.000000
 mean   1100.500000    0.363636    2.265550   30.272590    0.447368
 std     120.810458    0.481622    0.841838   14.181209    0.896760
 min     892.000000    0.000000    1.000000    0.170000    0.000000
 25%     996.250000    0.000000    1.000000   21.000000    0.000000
 50%    1100.500000    0.000000    3.000000   27.000000    0.000000
 75%    1204.750000    1.000000    3.000000   39.000000    1.000000
 max    1309.000000    1.000000    3.000000   76.000000    8.000000

             Parch        Fare
 count  418.000000  417.000000
 mean     0.392344   35.627188
 std      0.981429   55.907576
 min      0.000000    0.000000
 25%      0.000000    7.895800
 50%      0.000000   14.454200
 75%      0.000000   31.500000
 max      9.000000  512.329200  ,
 'Summary':         PassengerId    Survived      Pclass              Name   Sex  \
 count    418.000000  418.000000  418.000000               418   418
 unique          NaN         NaN         NaN               418     2
 top             NaN         NaN         NaN  Kelly, Mr. James  male
 freq            NaN         NaN         NaN                 1   266
 mean    1100.500000    0.363636    2.265550               NaN   NaN
 std      120.810458    0.481622    0.841838               NaN   NaN
 min      892.000000    0.000000    1.000000               NaN   NaN
 25%      996.250000    0.000000    1.000000               NaN   NaN
 50%     1100.500000    0.000000    3.000000               NaN   NaN
 75%     1204.750000    1.000000    3.000000               NaN   NaN
 max     1309.000000    1.000000    3.000000               NaN   NaN

                Age       SibSp       Parch    Ticket        Fare  \
 count   332.000000  418.000000  418.000000       418  417.000000
 unique         NaN         NaN         NaN       363         NaN
 top            NaN         NaN         NaN  PC 17608         NaN
 freq           NaN         NaN         NaN         5         NaN
 mean     30.272590    0.447368    0.392344       NaN   35.627188
 std      14.181209    0.896760    0.981429       NaN   55.907576
 min       0.170000    0.000000    0.000000       NaN    0.000000
 25%      21.000000    0.000000    0.000000       NaN    7.895800
 50%      27.000000    0.000000    0.000000       NaN   14.454200
 75%      39.000000    1.000000    0.000000       NaN   31.500000
 max      76.000000    8.000000    9.000000       NaN  512.329200

                   Cabin Embarked
 count                91      418
 unique               76        3
 top     B57 B59 B63 B66        S
 freq                  3      270
 mean                NaN      NaN
 std                 NaN      NaN
 min                 NaN      NaN
 25%                 NaN      NaN
 50%                 NaN      NaN
 75%                 NaN      NaN
 max                 NaN      NaN  }

Phase 2: Exploratory Data Analysis (EDA).

In [17]:
# Missing values in each column
missing_values = df.isnull().sum()
print(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [18]:
# Missing value percentage
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Values": missing_values,
    "Percentage (%)": missing_percentage.round(2)
})

print(missing_df.sort_values(by="Percentage (%)", ascending=False))

             Missing Values  Percentage (%)
Cabin                   327           78.23
Age                      86           20.57
Fare                      1            0.24
PassengerId               0            0.00
Survived                  0            0.00
Pclass                    0            0.00
Name                      0            0.00
Sex                       0            0.00
SibSp                     0            0.00
Parch                     0            0.00
Ticket                    0            0.00
Embarked                  0            0.00

# Duplicate Analysis

In [20]:
df.duplicated().sum()

0

# Unique Values Analysis

In [21]:
df.nunique()

PassengerId    418
Survived         2
Pclass           3
Name           418
Sex              2
Age             79
SibSp            7
Parch            8
Ticket         363
Fare           169
Cabin           76
Embarked         3
dtype: int64

In [22]:
unique_df = pd.DataFrame({
    "Data Type": df.dtypes,
    "Unique Values": df.nunique()
})

display(unique_df)

            Data Type  Unique Values
PassengerId     int64            418
Survived        int64              2
Pclass          int64              3
Name              str            418
Sex               str              2
Age           float64             79
SibSp           int64              7
Parch           int64              8
Ticket            str            363
Fare          float64            169
Cabin             str             76
Embarked          str              3

# Frequency Distribution (%)

In [25]:
gender_percent=(df["Sex"].value_counts(normalize=True).mul(100).round(2))
gender_percent

Sex
male      63.64
female    36.36
Name: proportion, dtype: float64

# Survival Percentage

In [28]:
survival_percent = (
    df["Survived"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)
display(survival_percent)

Survived
0    63.64
1    36.36
Name: proportion, dtype: float64

# Identify Numerical and Categorical Features

In [30]:
numerical_columns = df.select_dtypes(include=["number"]).columns
print(numerical_columns.tolist())

['PassengerId', 'Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [33]:
categorical_columns = df.select_dtypes(include=["object"]).columns

print(categorical_columns.tolist())

['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

C:\Users\nadim\AppData\Local\Temp\ipykernel_2632\1484338290.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns

# Summary

In [34]:
eda_summary = pd.DataFrame({
    "Data Type": df.dtypes,
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique(),
    "Missing (%)": ((df.isnull().sum() / len(df)) * 100).round(2)
})

display(eda_summary.sort_values("Missing (%)", ascending=False))

            Data Type  Missing Values  Unique Values  Missing (%)
Cabin             str             327             76        78.23
Age           float64              86             79        20.57
Fare          float64               1            169         0.24
PassengerId     int64               0            418         0.00
Survived        int64               0              2         0.00
Pclass          int64               0              3         0.00
Name              str               0            418         0.00
Sex               str               0              2         0.00
SibSp           int64               0              7         0.00
Parch           int64               0              8         0.00
Ticket            str               0            363         0.00
Embarked          str               0              3         0.00

# Handle Cabin

In [36]:
df["Deck"] = df["Cabin"].str[0]
df["Deck"]

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
      ...
413    NaN
414      C
415    NaN
416    NaN
417    NaN
Name: Deck, Length: 418, dtype: str

In [37]:
df["Deck"] = df["Deck"].fillna("U")

In [38]:
df = df.drop("Cabin", axis=1)

In [39]:
df["Deck"]

0      U
1      U
2      U
3      U
4      U
      ..
413    U
414    C
415    U
416    U
417    U
Name: Deck, Length: 418, dtype: str