In [2]:
import pandas as pd 
data = {
    "Name": [
        "Alice", "Bob", "Charlie", "David", 
        "David", "Eve", "Frank", "Grace", "Hannah", 
        "Ivy", "Jack"
    ],
    
    "City": [
        "New York", "Los Angeles", "Los Angeles", "Newark",
        "Boston", "New Delhi", "Chicago", "New Orleans", "Miami",
        "London", "Tokyo"
    ],
    
    "Department": [
        "HR", "IT", "Finance", "IT",
        "HR", "Marketing", "Finance", "HR",
        "IT", "Marketing", "Finance"
    ],
    
    "Salary": [
        50000, 60000, 55000, 70000,
        52000, 58000, 62000, 51000,
        65000, 72000, 68000
    ]
}

df = pd.DataFrame(data)

In [3]:
df

       Name         City Department  Salary
0     Alice     New York         HR   50000
1       Bob  Los Angeles         IT   60000
2   Charlie  Los Angeles    Finance   55000
3     David       Newark         IT   70000
4     David       Boston         HR   52000
5       Eve    New Delhi  Marketing   58000
6     Frank      Chicago    Finance   62000
7     Grace  New Orleans         HR   51000
8    Hannah        Miami         IT   65000
9       Ivy       London  Marketing   72000
10     Jack        Tokyo    Finance   68000

In [4]:
#filter
df.loc[df['City'].str.contains("New")]

    Name         City Department  Salary
0  Alice     New York         HR   50000
3  David       Newark         IT   70000
5    Eve    New Delhi  Marketing   58000
7  Grace  New Orleans         HR   51000

In [5]:
df.loc[df['City'].str.contains("new")] #case sensitive
df.loc[df['City'].str.contains("new", case=False)] #so we use parameter cas=false

    Name         City Department  Salary
0  Alice     New York         HR   50000
3  David       Newark         IT   70000
5    Eve    New Delhi  Marketing   58000
7  Grace  New Orleans         HR   51000

In [6]:
df.loc[df['City'].str.contains(r"los", case=False)]
df.loc[df['City'].str.contains(r"^los", case=False)] # it willl only start with the word los not all

      Name         City Department  Salary
1      Bob  Los Angeles         IT   60000
2  Charlie  Los Angeles    Finance   55000

In [7]:
df.loc[df['City'].str.contains(r"rk$", case=False)] #end use dolllar sign

    Name      City Department  Salary
0  Alice  New York         HR   50000
3  David    Newark         IT   70000

In [8]:
#name start with vowel
df.loc[df['Name'].str.contains(r"^[AEIOU]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
5    Eve  New Delhi  Marketing   58000
9    Ivy     London  Marketing   72000

In [9]:
df.loc[df['City'].str.contains(r"New|Los")] #will print new and los

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie  Los Angeles    Finance   55000
3    David       Newark         IT   70000
5      Eve    New Delhi  Marketing   58000
7    Grace  New Orleans         HR   51000

# Adding New Columns

In [10]:
df1=pd.read_csv('students.csv')
df1

                name course  credit  grade  cgpa
0        Hasan Ahmed  CS105       2   66.6  3.21
1          Imran Das  CS103       2   69.7  3.87
2       Sadia Sarker  CS102       4   79.9  2.31
3       Sadia Rahman  CS102       3   79.3  2.40
4       Sadia Sarker  CS102       4   78.6  2.43
..               ...    ...     ...    ...   ...
995      Ruma Sarker  CS104       3   75.8  2.25
996  Nadim Chowdhury  CS105       3   85.3  3.26
997     Salam Mondal  CS105       2   85.2  3.75
998      Karim Islam  CS101       3   80.2  3.99
999       Shila Khan  CS105       4   96.3  3.78

[1000 rows x 5 columns]

In [11]:
#constant value
df1['Country']="Bangladesh"
df1

                name course  credit  grade  cgpa     Country
0        Hasan Ahmed  CS105       2   66.6  3.21  Bangladesh
1          Imran Das  CS103       2   69.7  3.87  Bangladesh
2       Sadia Sarker  CS102       4   79.9  2.31  Bangladesh
3       Sadia Rahman  CS102       3   79.3  2.40  Bangladesh
4       Sadia Sarker  CS102       4   78.6  2.43  Bangladesh
..               ...    ...     ...    ...   ...         ...
995      Ruma Sarker  CS104       3   75.8  2.25  Bangladesh
996  Nadim Chowdhury  CS105       3   85.3  3.26  Bangladesh
997     Salam Mondal  CS105       2   85.2  3.75  Bangladesh
998      Karim Islam  CS101       3   80.2  3.99  Bangladesh
999       Shila Khan  CS105       4   96.3  3.78  Bangladesh

[1000 rows x 6 columns]

In [12]:
df1['State']="Sylhet"
df1

                name course  credit  grade  cgpa     Country   State
0        Hasan Ahmed  CS105       2   66.6  3.21  Bangladesh  Sylhet
1          Imran Das  CS103       2   69.7  3.87  Bangladesh  Sylhet
2       Sadia Sarker  CS102       4   79.9  2.31  Bangladesh  Sylhet
3       Sadia Rahman  CS102       3   79.3  2.40  Bangladesh  Sylhet
4       Sadia Sarker  CS102       4   78.6  2.43  Bangladesh  Sylhet
..               ...    ...     ...    ...   ...         ...     ...
995      Ruma Sarker  CS104       3   75.8  2.25  Bangladesh  Sylhet
996  Nadim Chowdhury  CS105       3   85.3  3.26  Bangladesh  Sylhet
997     Salam Mondal  CS105       2   85.2  3.75  Bangladesh  Sylhet
998      Karim Islam  CS101       3   80.2  3.99  Bangladesh  Sylhet
999       Shila Khan  CS105       4   96.3  3.78  Bangladesh  Sylhet

[1000 rows x 7 columns]

In [15]:
df1['Grade_Cgpa']=df1['grade']+ df1['cgpa']
df1

,name,course,credit,grade,cgpa,Country,State,Grade_Cgpa
0,Hasan Ahmed,CS105,2,66.6,3.21,Bangladesh,Sylhet,69.81
1,Imran Das,CS103,2,69.7,3.87,Bangladesh,Sylhet,73.57
2,Sadia Sarker,CS102,4,79.9,2.31,Bangladesh,Sylhet,82.21
3,Sadia Rahman,CS102,3,79.3,2.40,Bangladesh,Sylhet,81.70
4,Sadia Sarker,CS102,4,78.6,2.43,Bangladesh,Sylhet,81.03
...,...,...,...,...,...,...,...,...
995,Ruma Sarker,CS104,3,75.8,2.25,Bangladesh,Sylhet,78.05
996,Nadim Chowdhury,CS105,3,85.3,3.26,Bangladesh,Sylhet,88.56
997,Salam Mondal,CS105,2,85.2,3.75,Bangladesh,Sylhet,88.95
998,Karim Islam,CS101,3,80.2,3.99,Bangladesh,Sylhet,84.19
999,Shila Khan,CS105,4,96.3,3.78,Bangladesh,Sylhet,100.08

In [17]:
import numpy as np
df1['TopStudents']=np.where(df1['grade']>80, 'A+','A')
df1

,name,course,credit,grade,cgpa,Country,State,Grade_Cgpa,TopStudents
0,Hasan Ahmed,CS105,2,66.6,3.21,Bangladesh,Sylhet,69.81,A
1,Imran Das,CS103,2,69.7,3.87,Bangladesh,Sylhet,73.57,A
2,Sadia Sarker,CS102,4,79.9,2.31,Bangladesh,Sylhet,82.21,A
3,Sadia Rahman,CS102,3,79.3,2.40,Bangladesh,Sylhet,81.70,A
4,Sadia Sarker,CS102,4,78.6,2.43,Bangladesh,Sylhet,81.03,A
...,...,...,...,...,...,...,...,...,...
995,Ruma Sarker,CS104,3,75.8,2.25,Bangladesh,Sylhet,78.05,A
996,Nadim Chowdhury,CS105,3,85.3,3.26,Bangladesh,Sylhet,88.56,A+
997,Salam Mondal,CS105,2,85.2,3.75,Bangladesh,Sylhet,88.95,A+
998,Karim Islam,CS101,3,80.2,3.99,Bangladesh,Sylhet,84.19,A+
999,Shila Khan,CS105,4,96.3,3.78,Bangladesh,Sylhet,100.08,A+

In [15]:
df['firstname']=df['name'].str.split(' ').str[0]
df

,name,course,credit,grade,cgpa,Country,State,Grade_Cgpa,TopStudents,firstname
0,Hasan Ahmed,CS105,2,66.6,3.21,Bangladesh,Sylhet,69.81,A,Hasan
1,Imran Das,CS103,2,69.7,3.87,Bangladesh,Sylhet,73.57,A,Imran
2,Sadia Sarker,CS102,4,79.9,2.31,Bangladesh,Sylhet,82.21,A,Sadia
3,Sadia Rahman,CS102,3,79.3,2.40,Bangladesh,Sylhet,81.70,A,Sadia
4,Sadia Sarker,CS102,4,78.6,2.43,Bangladesh,Sylhet,81.03,A,Sadia
...,...,...,...,...,...,...,...,...,...,...
995,Ruma Sarker,CS104,3,75.8,2.25,Bangladesh,Sylhet,78.05,A,Ruma
996,Nadim Chowdhury,CS105,3,85.3,3.26,Bangladesh,Sylhet,88.56,A+,Nadim
997,Salam Mondal,CS105,2,85.2,3.75,Bangladesh,Sylhet,88.95,A+,Salam
998,Karim Islam,CS101,3,80.2,3.99,Bangladesh,Sylhet,84.19,A+,Karim
999,Shila Khan,CS105,4,96.3,3.78,Bangladesh,Sylhet,100.08,A+,Shila

In [18]:
df1.to_csv=('New_data.csv')

# Unique and null value checking

In [19]:
df=pd.read_csv('diabetes_data_upload.csv')

In [20]:
df

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,40,Male,No,Yes,No,Yes,No,No,No,Yes,No,Yes,No,Yes,Yes,Yes,Positive
1,58,Male,No,No,No,Yes,No,No,Yes,No,No,No,Yes,No,Yes,No,Positive
2,41,Male,Yes,No,No,Yes,Yes,No,No,Yes,No,Yes,No,Yes,Yes,No,Positive
3,45,Male,No,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes,No,No,No,No,Positive
4,60,Male,Yes,Yes,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Positive
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,39,Female,Yes,Yes,Yes,No,Yes,No,No,Yes,No,Yes,Yes,No,No,No,Positive
516,48,Female,Yes,Yes,Yes,Yes,Yes,No,No,Yes,Yes,Yes,Yes,No,No,No,Positive
517,58,Female,Yes,Yes,Yes,Yes,Yes,No,Yes,No,No,No,Yes,Yes,No,Yes,Positive
518,32,Female,No,No,No,Yes,No,No,Yes,Yes,No,Yes,No,No,Yes,No,Negative
519,42,Male,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Negative

In [21]:
df['Age'].unique() #unique works on only series
len(df['Age'].unique())

51

In [22]:
df['Polyuria'].nunique()

2

In [23]:
df.nunique()

Age                   51
Gender                 2
Polyuria               2
Polydipsia             2
sudden weight loss     2
weakness               2
Polyphagia             2
Genital thrush         2
visual blurring        2
Itching                2
Irritability           2
delayed healing        2
partial paresis        2
muscle stiffness       2
Alopecia               2
Obesity                2
class                  2
dtype: int64

In [24]:
#checkin null
df.isnull()

,Age,Gender,Polyuria,Polydipsia,sudden weight loss,weakness,Polyphagia,Genital thrush,visual blurring,Itching,Irritability,delayed healing,partial paresis,muscle stiffness,Alopecia,Obesity,class
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
516,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
517,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
518,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
519,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [25]:
df1.isnull()

,name,course,credit,grade,cgpa,Country,State,Grade_Cgpa,TopStudents
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False

In [26]:
df1['course'].isnull() #no null

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: course, Length: 1000, dtype: bool

In [27]:
df1['course'].notnull()

0      True
1      True
2      True
3      True
4      True
       ...
995    True
996    True
997    True
998    True
999    True
Name: course, Length: 1000, dtype: bool

In [28]:
df1['course'].hasnans

False

In [29]:
import pandas as pd

# Create a DataFrame with duplicates
data = {
    "ID": [101, 102, 103, 104, 102, 105, 106, 103],
    "Name": ["Alice", "Bob", "Charlie", "David", "Bob", "Eva", "Frank", "Charlie"],
    "Department": ["HR", "IT", "Finance", "Marketing", "IT", "HR", "Finance", "Finance"],
    "Salary": [5000, 6000, 7000, 8000, 6000, 5500, 7200, 7000]
}

df = pd.DataFrame(data)

print(df)

    ID     Name Department  Salary
0  101    Alice         HR    5000
1  102      Bob         IT    6000
2  103  Charlie    Finance    7000
3  104    David  Marketing    8000
4  102      Bob         IT    6000
5  105      Eva         HR    5500
6  106    Frank    Finance    7200
7  103  Charlie    Finance    7000

In [30]:
df.duplicated() #duplicate True Otherwise False

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
dtype: bool

In [31]:
df.duplicated().sum()

2

In [32]:
#deleting duplicate
df.drop_duplicates(inplace=True) #permannet delete

In [33]:
df

    ID     Name Department  Salary
0  101    Alice         HR    5000
1  102      Bob         IT    6000
2  103  Charlie    Finance    7000
3  104    David  Marketing    8000
5  105      Eva         HR    5500
6  106    Frank    Finance    7200

In [34]:
#colum wise delete
df.drop_duplicates(subset=['Name'])

    ID     Name Department  Salary
0  101    Alice         HR    5000
1  102      Bob         IT    6000
2  103  Charlie    Finance    7000
3  104    David  Marketing    8000
5  105      Eva         HR    5500
6  106    Frank    Finance    7200

In [35]:
df.drop_duplicates(subset=['Department']) #it delete the last one manually

    ID     Name Department  Salary
0  101    Alice         HR    5000
1  102      Bob         IT    6000
2  103  Charlie    Finance    7000
3  104    David  Marketing    8000

In [36]:
df.drop_duplicates(subset=['Department'],keep='last') #keeps the last value

    ID   Name Department  Salary
1  102    Bob         IT    6000
3  104  David  Marketing    8000
5  105    Eva         HR    5500
6  106  Frank    Finance    7200

# handling null values

In [37]:
import pandas as pd

# Create a Students DataFrame
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Hannah"],
    "Age": [20, 21, None, 22, 20, None, 23, 21],
    "Gender": ["Female", "Male", "Male", "Male", "Female", None, "Female", "Female"],
    "Department": ["CS", "IT", "CS", "SE", None, "IT", "SE", "CS"],
    "CGPA": [3.85, 3.60, None, 3.20, 3.95, 3.40, 3.75, 3.90],
    "Email": [
        "alice@example.com",
        "bob@example.com",
        "charlie@example.com",
        "david@example.com",
        None,
        None,
        "grace@example.com",
        "hannah@example.com"
    ]
}

df = pd.DataFrame(data)

print(df)

   Student_ID     Name   Age  Gender Department  CGPA                Email
0         101    Alice  20.0  Female         CS  3.85    alice@example.com
1         102      Bob  21.0    Male         IT  3.60      bob@example.com
2         103  Charlie   NaN    Male         CS   NaN  charlie@example.com
3         104    David  22.0    Male         SE  3.20    david@example.com
4         105      Eva  20.0  Female        NaN  3.95                  NaN
5         106    Frank   NaN     NaN         IT  3.40                  NaN
6         107    Grace  23.0  Female         SE  3.75    grace@example.com
7         108   Hannah  21.0  Female         CS  3.90   hannah@example.com

In [38]:
df.dropna() #deletes all null value rows

   Student_ID    Name   Age  Gender Department  CGPA               Email
0         101   Alice  20.0  Female         CS  3.85   alice@example.com
1         102     Bob  21.0    Male         IT  3.60     bob@example.com
3         104   David  22.0    Male         SE  3.20   david@example.com
6         107   Grace  23.0  Female         SE  3.75   grace@example.com
7         108  Hannah  21.0  Female         CS  3.90  hannah@example.com

In [39]:
df.dropna(how='all',inplace=True) #if a rows contains null values all it will only delete that row

In [40]:
df

   Student_ID     Name   Age  Gender Department  CGPA                Email
0         101    Alice  20.0  Female         CS  3.85    alice@example.com
1         102      Bob  21.0    Male         IT  3.60      bob@example.com
2         103  Charlie   NaN    Male         CS   NaN  charlie@example.com
3         104    David  22.0    Male         SE  3.20    david@example.com
4         105      Eva  20.0  Female        NaN  3.95                  NaN
5         106    Frank   NaN     NaN         IT  3.40                  NaN
6         107    Grace  23.0  Female         SE  3.75    grace@example.com
7         108   Hannah  21.0  Female         CS  3.90   hannah@example.com

In [41]:
#colum wlise 
df.dropna(subset='Department')

   Student_ID     Name   Age  Gender Department  CGPA                Email
0         101    Alice  20.0  Female         CS  3.85    alice@example.com
1         102      Bob  21.0    Male         IT  3.60      bob@example.com
2         103  Charlie   NaN    Male         CS   NaN  charlie@example.com
3         104    David  22.0    Male         SE  3.20    david@example.com
5         106    Frank   NaN     NaN         IT  3.40                  NaN
6         107    Grace  23.0  Female         SE  3.75    grace@example.com
7         108   Hannah  21.0  Female         CS  3.90   hannah@example.com

In [42]:
df.fillna(0) #null values will change to 0

   Student_ID     Name   Age  Gender Department  CGPA                Email
0         101    Alice  20.0  Female         CS  3.85    alice@example.com
1         102      Bob  21.0    Male         IT  3.60      bob@example.com
2         103  Charlie   0.0    Male         CS  0.00  charlie@example.com
3         104    David  22.0    Male         SE  3.20    david@example.com
4         105      Eva  20.0  Female          0  3.95                    0
5         106    Frank   0.0       0         IT  3.40                    0
6         107    Grace  23.0  Female         SE  3.75    grace@example.com
7         108   Hannah  21.0  Female         CS  3.90   hannah@example.com

In [43]:
df['Department'] = df['Department'].fillna('unknown')

In [44]:
df

   Student_ID     Name   Age  Gender Department  CGPA                Email
0         101    Alice  20.0  Female         CS  3.85    alice@example.com
1         102      Bob  21.0    Male         IT  3.60      bob@example.com
2         103  Charlie   NaN    Male         CS   NaN  charlie@example.com
3         104    David  22.0    Male         SE  3.20    david@example.com
4         105      Eva  20.0  Female    unknown  3.95                  NaN
5         106    Frank   NaN     NaN         IT  3.40                  NaN
6         107    Grace  23.0  Female         SE  3.75    grace@example.com
7         108   Hannah  21.0  Female         CS  3.90   hannah@example.com

In [45]:
df['CGPA'] = df['CGPA'].fillna(df['CGPA'].mean())

In [46]:
df

   Student_ID     Name   Age  Gender Department      CGPA                Email
0         101    Alice  20.0  Female         CS  3.850000    alice@example.com
1         102      Bob  21.0    Male         IT  3.600000      bob@example.com
2         103  Charlie   NaN    Male         CS  3.664286  charlie@example.com
3         104    David  22.0    Male         SE  3.200000    david@example.com
4         105      Eva  20.0  Female    unknown  3.950000                  NaN
5         106    Frank   NaN     NaN         IT  3.400000                  NaN
6         107    Grace  23.0  Female         SE  3.750000    grace@example.com
7         108   Hannah  21.0  Female         CS  3.900000   hannah@example.com

# statistical functions in pandas

In [47]:
df

   Student_ID     Name   Age  Gender Department      CGPA                Email
0         101    Alice  20.0  Female         CS  3.850000    alice@example.com
1         102      Bob  21.0    Male         IT  3.600000      bob@example.com
2         103  Charlie   NaN    Male         CS  3.664286  charlie@example.com
3         104    David  22.0    Male         SE  3.200000    david@example.com
4         105      Eva  20.0  Female    unknown  3.950000                  NaN
5         106    Frank   NaN     NaN         IT  3.400000                  NaN
6         107    Grace  23.0  Female         SE  3.750000    grace@example.com
7         108   Hannah  21.0  Female         CS  3.900000   hannah@example.com

In [48]:
df.dropna()

   Student_ID    Name   Age  Gender Department  CGPA               Email
0         101   Alice  20.0  Female         CS  3.85   alice@example.com
1         102     Bob  21.0    Male         IT  3.60     bob@example.com
3         104   David  22.0    Male         SE  3.20   david@example.com
6         107   Grace  23.0  Female         SE  3.75   grace@example.com
7         108  Hannah  21.0  Female         CS  3.90  hannah@example.com

In [49]:
df['CGPA'].sum()

29.314285714285713

In [50]:
df['Age'].sum()

127.0

In [51]:
df['CGPA'].max() #max value

3.95

In [52]:
df['CGPA'].min() #min value

3.2

In [53]:
#mean 
df['CGPA'].mean()

3.664285714285714

In [54]:
df['CGPA'].median()

3.7071428571428573

In [55]:
#mode 
df['CGPA'].mode()

0    3.200000
1    3.400000
2    3.600000
3    3.664286
4    3.750000
5    3.850000
6    3.900000
7    3.950000
Name: CGPA, dtype: float64

In [56]:
#std 
df['CGPA'].std()

0.25872528966106906

In [57]:
#correlation matrix 
df[['Age','CGPA']].corr()

           Age      CGPA
Age   1.000000 -0.497018
CGPA -0.497018  1.000000

In [58]:
df=pd.read_csv('student_data (1).csv')

In [59]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [60]:
df[['Data Structure Marks','Algorithm Marks']].corr()

                      Data Structure Marks  Algorithm Marks
Data Structure Marks                   1.0              1.0
Algorithm Marks                        1.0              1.0

In [61]:
df[['Data Structure Marks','Python Marks']].corr()

                      Data Structure Marks  Python Marks
Data Structure Marks              1.000000      0.893455
Python Marks                      0.893455      1.000000

In [62]:
#sum in different columns
df[['Data Structure Marks','Algorithm Marks']].sum()

Data Structure Marks    1344.0
Algorithm Marks         1344.0
dtype: float64

In [63]:
#sum in different columns row  wise 
df[['Data Structure Marks','Algorithm Marks']].sum(axis=1)

0     170.0
1     184.0
2     176.0
3     156.0
4       0.0
5     150.0
6     160.0
7     162.0
8     144.0
9     178.0
10      0.0
11    170.0
12    150.0
13      0.0
14    172.0
15    188.0
16    180.0
17    176.0
18      0.0
19    172.0
dtype: float64

In [64]:
df.set_index('FullName')[['Data Structure Marks', 'Algorithm Marks']].sum(axis=1)

FullName
Alif Rahman         170.0
Fatima Akhter       184.0
Imran Hossain       176.0
Jannatul Ferdous    156.0
Kamal Uddin           0.0
Laila Begum         150.0
Mahmudul Hasan      160.0
Nadia Islam         162.0
Omar Faruq          144.0
Priya Sharma        178.0
Rahim Sheikh          0.0
Sadia Chowdhury     170.0
Tanvir Ahmed        150.0
Urmi Akter            0.0
Wahiduzzaman        172.0
Ziaur Rahman        188.0
Afsana Mimi         180.0
Babul Ahmed         176.0
Faria Rahman          0.0
Nasir Khan          172.0
dtype: float64

In [65]:
# Calculate row-wise sum with FullName as index, and get the top 1 row
df.set_index('FullName')[['Data Structure Marks', 'Algorithm Marks']].sum(axis=1).nlargest(1)

FullName
Ziaur Rahman    188.0
dtype: float64

In [66]:
df[['Data Structure Marks', 'Algorithm Marks']].max()

Data Structure Marks    94.0
Algorithm Marks         94.0
dtype: float64

In [69]:
df['Total_marks']=df.iloc[::,2:5].sum(axis=1) #row wise
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0

# apply function in df

In [70]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0

In [75]:
#min max scalling
mn=df['Total_marks'].min()
print(mn)
mx=df['Total_marks'].max()
mx

0.0

273.0

# Scaled=(x-min)/(mx-mn)

In [79]:
df['Scaled_marks']=df['Total_marks'].apply(lambda x:(x-mn)/(mx-mn))

In [80]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total_marks,Scaled_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044

In [83]:
#custom built in function 
def grading_system(marks):
    if marks >=260:
        return 'A'
    elif marks>=250:
        return 'A'
    else:
        return 'A-' #created custom built inn function 
df['Grade']=df['Total_marks'].apply(grading_system)

In [84]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total_marks,Scaled_marks,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055,A
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993,A-
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044,A
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795,A-
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985,A-
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165,A-
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081,A-
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762,A-
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861,A-
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359,A
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333,A-
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828,A-
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000,A-
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729,A
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645,A-
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000,A
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044,A
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000,A-
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044,A

In [86]:
#all dataframe 
def marking_system(df):
    a=df['Data Structure Marks']*2
    b=df['Python Marks']*3
    c=df['Algorithm Marks']*4 
    return a+b+c

 
df['Excceptional_Marks']=df.apply(marking_system,axis=1)

In [87]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Total_marks,Scaled_marks,Grade,Excceptional_Marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,258.0,0.945055,A,774.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,184.0,0.673993,A-,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,261.0,0.956044,A,783.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,238.0,0.871795,A-,714.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,95.0,0.347985,A-,NaN
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,228.0,0.835165,A-,684.0
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,160.0,0.586081,A-,NaN
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,247.0,0.904762,A-,741.0
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,220.0,0.805861,A-,660.0
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,266.0,0.974359,A,798.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,91.0,0.333333,A-,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,257.0,0.941392,A,771.0
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,229.0,0.838828,A-,687.0
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,0.0,0.000000,A-,NaN
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,256.0,0.937729,A,768.0
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,188.0,0.688645,A-,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,273.0,1.000000,A,819.0
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,261.0,0.956044,A,783.0
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,0.0,0.000000,A-,NaN
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,261.0,0.956044,A,783.0

# Date time and Time delta

In [88]:
df=pd.read_csv('student_completed_data.csv')

In [89]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [90]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: str

In [93]:
#to convert in pandas dataframe 
df['EnrollmentDate']=pd.to_datetime(df['EnrollmentDate'])

In [94]:
df['EnrollmentDate'] #changed datatype to datetime

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[us]

In [95]:
df['Enrollment_year']=df['EnrollmentDate'].dt.year

In [96]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024

In [97]:
df['Enrollment_month']=df['EnrollmentDate'].dt.month

In [98]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7

In [106]:
df['FinishedDate']=pd.to_datetime(df['FinishedDate'])

In [108]:
df['FinishedDate']

0    2024-12-23
1    2024-11-07
2    2024-08-08
3    2024-09-23
4    2024-04-17
5    2024-12-31
6    2024-07-20
7    2024-05-01
8    2024-06-08
9    2024-08-19
10   2024-06-11
11   2024-10-25
12   2024-08-03
13   2024-03-23
14   2024-05-16
15   2024-06-21
16   2024-03-16
17   2024-09-20
18   2024-08-17
19   2024-10-11
Name: FinishedDate, dtype: datetime64[us]

In [109]:
df['Total_timetakentofinish']=df['FinishedDate'] - df['EnrollmentDate']

In [110]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9,2024-12-23,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8,2024-11-07,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5,2024-08-08,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7,2024-09-23,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2,2024-04-17,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9,2024-12-31,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6,2024-07-20,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3,2024-05-01,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2,2024-06-08,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6,2024-08-19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3,2024-06-11,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8,2024-10-25,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6,2024-08-03,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1,2024-03-23,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2,2024-05-16,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3,2024-06-21,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1,2024-03-16,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6,2024-09-20,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4,2024-08-17,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7,2024-10-11,82 days

In [111]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9,2024-12-23,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8,2024-11-07,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5,2024-08-08,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7,2024-09-23,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2,2024-04-17,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9,2024-12-31,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6,2024-07-20,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3,2024-05-01,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2,2024-06-08,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6,2024-08-19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3,2024-06-11,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8,2024-10-25,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6,2024-08-03,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1,2024-03-23,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2,2024-05-16,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3,2024-06-21,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1,2024-03-16,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6,2024-09-20,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4,2024-08-17,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7,2024-10-11,82 days

# Group by function in pandas

In [114]:
 instructor_group=df.groupby('Instructor')
instructor_group #created a object

In [116]:
for instructor,df_ins in instructor_group:
    print(instructor)
    display(df_ins)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2,2024-04-17,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9,2024-12-31,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6,2024-07-20,43 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6,2024-08-19,61 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6,2024-08-03,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1,2024-03-23,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2,2024-05-16,84 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1,2024-03-16,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6,2024-09-20,89 days

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8,2024-11-07,88 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7,2024-09-23,80 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2,2024-06-08,117 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3,2024-06-11,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8,2024-10-25,82 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4,2024-08-17,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7,2024-10-11,82 days

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9,2024-12-23,113 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5,2024-08-08,92 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3,2024-05-01,40 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3,2024-06-21,90 days

In [126]:
#df.min()



instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
Instructor,,,,,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,2024-01-04,2024-03-16,Chattogram,236,2024,1,2024-03-16,43 days
Mr. Karim,PH0002,Faria Rahman,Completed,2024-02-12,2024-06-08,Dhaka,253,2024,2,2024-06-08,80 days
Ms. Salma,PH0001,Alif Rahman,Completed,2024-03-22,2024-05-01,Dhaka,234,2024,3,2024-05-01,40 days

In [124]:
instructor_group.describe()

           EnrollmentDate                                                   \
                    count                        mean                  min
Instructor
Mr. David               9         2024-04-22 13:20:00  2024-01-04 00:00:00
Mr. Karim               7  2024-05-30 03:25:42.857142  2024-02-12 00:00:00
Ms. Salma               4         2024-05-13 18:00:00  2024-03-22 00:00:00

                                                                           \
                            25%                  50%                  75%
Instructor
Mr. David   2024-02-01 00:00:00  2024-06-07 00:00:00  2024-06-19 00:00:00
Mr. Karim   2024-04-01 00:00:00  2024-07-05 00:00:00  2024-07-28 00:00:00
Ms. Salma   2024-03-22 18:00:00  2024-04-15 00:00:00  2024-06-06 00:00:00

                                     FinishedDate                              \
                            max  std        count                        mean
Instructor
Mr. David   2024-09-07 00:00:00  NaN            9         2024-07-05 02:40:00
Mr. Karim   2024-08-11 00:00:00  NaN            7  2024-09-01 03:25:42.857142
Ms. Salma   2024-09-01 00:00:00  NaN            4         2024-08-05 12:00:00

            ...          Finish_date      Total_timetakentofinish  \
            ...                  max  std                   count
Instructor  ...
Mr. David   ...  2024-12-31 00:00:00  NaN                       9
Mr. Karim   ...  2024-11-07 00:00:00  NaN                       7
Ms. Salma   ...  2024-12-23 00:00:00  NaN                       4

                                                                  \
                        mean               min               25%
Instructor
Mr. David   73 days 13:20:00  43 days 00:00:00  58 days 00:00:00
Mr. Karim   94 days 00:00:00  80 days 00:00:00  82 days 00:00:00
Ms. Salma   83 days 18:00:00  40 days 00:00:00  77 days 12:00:00

                                                                    \
                         50%                75%                max
Instructor
Mr. David   76 days 00:00:00   84 days 00:00:00  115 days 00:00:00
Mr. Karim   88 days 00:00:00  103 days 00:00:00  120 days 00:00:00
Ms. Salma   91 days 00:00:00   97 days 06:00:00  113 days 00:00:00


                                std
Instructor
Mr. David   21 days 12:42:45.670041
Mr. Karim   17 days 01:52:40.910298
Ms. Salma   30 days 23:11:35.199023

[3 rows x 56 columns]

In [130]:
mean_marks=instructor_group['Total Marks'].mean()
mean_marks

Instructor
Mr. David    266.555556
Mr. Karim    273.000000
Ms. Salma    262.250000
Name: Total Marks, dtype: float64

In [134]:
df['Total Marks']=df['Total Marks'].fillna(df['Instructor'].map(mean_marks))
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment_year,Enrollment_month,Finish_date,Total_timetakentofinish
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9,2024-12-23,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8,2024-11-07,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5,2024-08-08,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7,2024-09-23,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2,2024-04-17,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9,2024-12-31,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6,2024-07-20,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3,2024-05-01,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2,2024-06-08,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6,2024-08-19,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3,2024-06-11,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8,2024-10-25,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6,2024-08-03,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1,2024-03-23,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2,2024-05-16,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3,2024-06-21,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1,2024-03-16,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6,2024-09-20,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4,2024-08-17,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7,2024-10-11,82 days